### ISSUE TITLE
Videos not saving on the folder selected

### ISSUE THREAD

**Issue by pootz10** [EGirlEnthusiast/Coomer.party-scraper#6]
I used it for the first time yesterday and everything worked as it says, but later I released the videos were not in the folder I specified as the images were, all the videos were inside the .py file folder.
Modifying the line
`with open(str(number)+'.mp4', 'wb') as handler:`
to
`with open(f'{file_path}/Videos/{str(number)}.mp4', 'wb') as handler:`
solved my problem.

**Comment by taux1c** [comment]
Nice catch good sir!
